### ISSUE TITLE
UEDX48480021-MD80ESP32_2.1inch-Knob

### ISSUE THREAD

**Issue by klattimer** [sEbola76/gc9503v#1]
I'm trying to get this working with the following device. 

I've managed to get some coloured stripes on the screen, but they weird and faded, I think I've got he pin configuration correct now at least but still no joy with a proper test card. 

https://github.com/VIEWESMART/UEDX48480021-MD80ESP32_2.1inch-Knob

Do you have any pointers for debugging it?

**Comment by sEbola76** [comment]
> I'm trying to get this working with the following device.
> 
> I've managed to get some coloured stripes on the screen, but they weird and faded, I think I've got he pin configuration correct now at least but still no joy with a proper test card.
> 
> https://github.com/VIEWESMART/UEDX48480021-MD80ESP32_2.1inch-Knob
> 
> Do you have any pointers for debugging it?

Can You make and send a photo?

**Comment by onlytobeking** [comment]
@klattimer Have you had any progress on this? Im having the same device and hoping I can get it working with esphome. @sEbola76 what kind of photos do you need? I have it taken apart right now so I can provide photos.

**Comment by klattimer** [comment]
![Image](https://github.com/user-attachments/assets/4443cd56-7d78-4c16-8d55-58be9f874f59)

This is what I'm getting on the screen, it's very faded, sometimes different but more or less the same.

**Comment by klattimer** [comment]
Here's my display config
```yaml
display:
  - platform: gc9503v
    update_interval: 1s
    #show_test_card: true
    # update_interval: never
    auto_clear_enabled: true
    show_test_card: true
    id: my_display
    color_order: RGB
    dimensions:
      width: 480
      height: 480  
    de_pin:
      number: 17
      inverted: false
    hsync_pin:
      number: 46
      inverted: false
    vsync_pin:
      number: 3
      inverted: false
    pclk_pin: 9
    pclk_inverted: true
    hsync_pulse_width: 10
    hsync_front_porch: 8
    hsync_back_porch: 40
    vsync_pulse_width: 10
    vsync_front_porch: 8
    vsync_back_porch: 40
    data_pins:
      red:
        - number: 13 # R1 13
          allow_other_uses: true
        - 14         # R2 14
        - 21         # R3 21
        - 47         # R4 47
        - 48         # R5 48
      green:
        - 42         # G0 42
        - 2          # G1 2
        - 1          # G2 1
        - 10         # G3 10
        - 11         # G4 11
        - number: 12 # G5 12 
          allow_other_uses: true
      blue:
        - 45         # B1 
        - 38         # B2 38
        - 39         # B3 39
        - 40         # B4 40
        - 41         # B5 41
    enable_pin:
      number: 18
      inverted: true
    reset_pin:
      number: 8
      inverted: false
    sclk_pin:
      number: 13
      allow_other_uses: true
    mosi_pin:
      number: 12
      allow_other_uses: true

```
